#ifndef OPENJAUS_STRUCTURES_H
#define OPENJAUS_STRUCTURES_H

//! Structure to hold the contents of a JAUS ReportGlobalPose message
struct GlobalPose {
    double latitude_deg; //!< lattitude in degrees
    double longitude_deg; //!< longitude in degrees
    double altitude_m; //!< altitude in meters
    double positionRMS_m; //!< position accuracy (RMS) in meters
    double roll_rad; //!< roll angle in radians
    double pitch_rad; //!< pitch angle in radians
    double yaw_rad; //!< yaw angle in radians
    double attitudeRMS_rad; //!< attitude accuracy (RMS) in radians
    double timeStamp; //!< time stamp
};

struct Service {

};

struct Component {

};

struct Node {

};

//! Structure to hold a JAUS system tree generated by the discovery service
struct SystemTree {

};

#endif // OPENJAUS_STRUCTURES_H
